id: IBED0803D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:36:28+00:00'
last_modified: '2022-06-09T07:27:54.733012+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24747
  title: གེ་སར་རིག་པའི་སློབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '3077':
      image_group_id: I1KG24749
      title: Volume 1 of ge ser rig pa'i slob deb/
      total_pages: 677
      order: 1
      base_file: 3077.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
