id: P007917
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24747
  title: གེ་སར་རིག་པའི་སློབ་དེབ།
  author: ''
  volumes:
    143150699c3545749c86cfbb0717956d:
      image_group_id: I1KG24749
      title: ''
      volume_number: 1
      total_pages: 677
ebook_metadata:
  title: གེ་སར་རིག་པའི་སློབ་དེབ།
  author: ''
  sku: P007917
  cover: cover.jpg
  layers:
  - pagination
